### ISSUE TITLE
Environment processing chokes when "modules" installed

### ISSUE THREAD

**Issue by bnordgren** [elasticluster/elasticluster#675] opened 2020-03-05 17:02 UTC
On Fedora silverblue 31 with package environment-modules-4.3.0-1.fc31.x86_64 installed, the environment has many many multi line variables, which are really functions. This results in: 

```
[bnordgren@brycelap ~]$ ./elasticluster list-templates
Error: unable to process environment variables: name "if [ \"${MODULES_USE_COMPAT_VERSION:-0}\" " has white spaces, poorly formatted name
```

I'm thinking I may have to find a machine without environment modules installed?  Relevant excerpt from the output of "env":

```
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
BASH_FUNC_switchml%%=() {  typeset swfound=1;
 if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
 typeset swname='main';
 if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
 typeset swfound=0;
 unset MODULES_USE_COMPAT_VERSION;
 fi;
 else
 typeset swname='compatibility';
 if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
 typeset swfound=0;
 MODULES_USE_COMPAT_VERSION=1;
 export MODULES_USE_COMPAT_VERSION;
 fi;
 fi;
 if [ $swfound -eq 0 ]; then
 echo "Switching to Modules $swname version";
 source /usr/share/Modules/init/bash;
 else
 echo "Cannot switch to Modules $swname version, command not found";
 return 1;
 fi
}
BASH_FUNC_module%%=() {  _module_raw "$@" 2>&1
}
BASH_FUNC_scl%%=() {  if [ "$1" = "load" -o "$1" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
BASH_FUNC__module_raw%%=() {  unset _mlshdbg;
 if [ "${MODULES_SILENT_SHELL_DEBUG:-0}" = '1' ]; then
 case "$-" in 
 *v*x*)
 set +vx;
 _mlshdbg='vx'
 ;;
 *v*)
 set +v;
 _mlshdbg='v'
 ;;
 *x*)
 set +x;
 _mlshdbg='x'
 ;;
 *)
 _mlshdbg=''
 ;;
 esac;
 fi;
 unset _mlre _mlIFS;
 if [ -n "${IFS+x}" ]; then
 _mlIFS=$IFS;
 fi;
 IFS=' ';
 for _mlv in ${MODULES_RUN_QUARANTINE:-};
 do
 if [ "${_mlv}" = "${_mlv##*[!A-Za-z0-9_]}" -a "${_mlv}" = "${_mlv#[0-9]}" ]; then
 if [ -n "`eval 'echo ${'$_mlv'+x}'`" ]; then
 _mlre="${_mlre:-}${_mlv}_modquar='`eval 'echo ${'$_mlv'}'`' ";
 fi;
 _mlrv="MODULES_RUNENV_${_mlv}";
 _mlre="${_mlre:-}${_mlv}='`eval 'echo ${'$_mlrv':-}'`' ";
 fi;
 done;
 if [ -n "${_mlre:-}" ]; then
 eval `eval ${_mlre}/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash '"$@"'`;
 else
 eval `/usr/bin/tclsh /usr/share/Modules/libexec/modulecmd.tcl bash "$@"`;
 fi;
 _mlstatus=$?;
 if [ -n "${_mlIFS+x}" ]; then
 IFS=$_mlIFS;
 else
 unset IFS;
 fi;
 unset _mlre _mlv _mlrv _mlIFS;
 if [ -n "${_mlshdbg:-}" ]; then
 set -$_mlshdbg;
 fi;
 unset _mlshdbg;
 return $_mlstatus
}
_=/usr/bin/env
```

**Comment by riccardomurri** [comment] 2020-03-06 08:57
Are you using the Dockerized version of ElastiCluster? (a.k.a. `elasticluster.sh`)

**Comment by bnordgren** [comment] 2020-03-06 18:15
Yup. I renamed `elasticluster.sh` to `elasticluster` in order to match the examples better.

**Comment by riccardomurri** [comment] 2020-03-06 21:45
Can you please try again with the latest `elasticluster.sh` in the "master" banch? (commit bb4a3278)

You will need to download it again, there's no auto-update mechanism for the script itself.

**Comment by bnordgren** [comment] 2020-03-10 21:43
Didn't seem to help...
```
[bnordgren@mine ~]$ sh -x ./elasticluster list-templates
++ basename ./elasticluster
+ me=elasticluster
+ docker_image_name=riccardomurri/elasticluster
+ docker_image_tag=latest
+ EX_OK=0
+ EX_USAGE=1
+ EX_DATAERR=65
+ EX_NOINPUT=66
+ EX_NOUSER=67
+ EX_NOHOST=68
+ EX_UNAVAILABLE=69
+ EX_SOFTWARE=70
+ EX_OSERR=71
+ EX_OSFILE=72
+ EX_CANTCREAT=73
+ EX_IOERR=74
+ EX_TEMPFAIL=75
+ EX_PROTOCOL=76
+ EX_NOPERM=77
+ EX_CONFIG=78
+ have_command tput
+ command -v tput
++ tput sgr0
+ TXT_NORMAL=''
++ tput bold
+ TXT_BOLD=''
++ tput dim
+ TXT_DIM=''
++ tput smso
+ TXT_STANDOUT=''
++ tput setaf 0
+ TXT_BLACK=''
++ tput setaf 4
+ TXT_BLUE=''
++ tput setaf 6
+ TXT_CYAN=''
++ tput setaf 2
+ TXT_GREEN=''
++ tput setaf 5
+ TXT_MAGENTA=''
++ tput setaf 1
+ TXT_RED=''
++ tput setaf 7
+ TXT_WHITE=''
++ tput setaf 3
+ TXT_YELLOW=''
++ tput op
+ TXT_NOCOLOR=''
+ have_command docker
+ command -v docker
+ require_command egrep
+ have_command egrep
+ command -v egrep
+ require_command env
+ have_command env
+ command -v env
+ require_command docker
+ have_command docker
+ command -v docker
+ require_command readlink
+ have_command readlink
+ command -v readlink
+ env -0
+ env_has_null_termination_opt=y
+ require_command awk
+ have_command awk
+ command -v awk
+ volumes='-v /home/bnordgren/.ssh:/home/.ssh -v /home/bnordgren/.elasticluster:/home/.elasticluster'
+ '[' -n /run/user/1000/keyring/ssh ']'
+ volumes='-v /home/bnordgren/.ssh:/home/.ssh -v /home/bnordgren/.elasticluster:/home/.elasticluster -v /run/user/1000/keyring/ssh:/home/.ssh-agent.sock'
+ '[' -d /home/bnordgren/.config ']'
+ volumes='-v /home/bnordgren/.ssh:/home/.ssh -v /home/bnordgren/.elasticluster:/home/.elasticluster -v /run/user/1000/keyring/ssh:/home/.ssh-agent.sock -v /home/bnordgren/.config:/home/.config'
+ argv=
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ argv=' list-templates'
+ shift
+ '[' 0 -gt 0 ']'
+ set -- list-templates
+ elasticluster_docker_image=riccardomurri/elasticluster:latest
+ '[' '' = yes ']'
++ id -u
+ '[' 1000 -eq 0 ']'
+ for arg in "$@"
+ '[' list-templates = sftp ']'
+ for dir in "$HOME/.ssh" "$HOME/.elasticluster"
+ test -d /home/bnordgren/.ssh
+ for dir in "$HOME/.ssh" "$HOME/.elasticluster"
+ test -d /home/bnordgren/.elasticluster
++ mktemp -t elasticluster.XXXXXXXXXXXX.env
+ envfile=/tmp/elasticluster.QUl5O2DtJLj2.env
+ '[' -z /tmp/elasticluster.QUl5O2DtJLj2.env ']'
+ trap 'rm -f '\''/tmp/elasticluster.QUl5O2DtJLj2.env'\'';' EXIT INT QUIT ABRT TERM
+ '[' y = y ']'
+ env -0 HOME=/home/bnordgren SHELL=/bin/sh SSH_AUTH_SOCK=/home/.ssh-agent.sock
+ awk 'BEGIN { RS="\0"; FS="="; }; { if ($2 !~ /\n/) print; };'
+ egrep -v '^(BASH_ENV|ENV|PROMPT_COMMAND|PS[1234])='
+ exec docker run --rm --interactive --tty --env-file /tmp/elasticluster.QUl5O2DtJLj2.env -v /home/bnordgren/.ssh:/home/.ssh -v /home/bnordgren/.elasticluster:/home/.elasticluster -v /run/user/1000/keyring/ssh:/home/.ssh-agent.sock -v /home/bnordgren/.config:/home/.config riccardomurri/elasticluster:latest list-templates
docker: poorly formatted environment: variable 'if [ "${MODULES_USE_COMPAT_VERSION:-0}" ' has white spaces.
See 'docker run --help'.
[bnordgren@mine ~]$ 
```

**Comment by riccardomurri** [comment] 2020-03-10 21:52
I'm puzzled... what does this print in your terminal?
```
env -0 XXX1=foobar XXX2=$'foo\nbar' | awk 'BEGIN { RS="\0"; FS="="; }; { if ($2 !~ /\n/) print; };'
```

**Comment by bnordgren** [comment] 2020-03-10 22:08
```[bnordgren@mine ~]$ env -0 XXX1=foobar XXX2=$'foo\nbar' | awk 'BEGIN { RS="\0"; FS="="; }; { if ($2 !~ /\n/) print; };'
SHELL=/bin/bash
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1746,unix/unix:/tmp/.ICE-unix/1746
COLORTERM=truecolor
HISTCONTROL=ignoredups
XDG_MENU_PREFIX=gnome-
HISTSIZE=1000
HOSTNAME=mine.usfs-i2.umt.edu
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
XMODIFIERS=@im=ibus
DESKTOP_SESSION=gnome
PWD=/home/bnordgren
LOGNAME=bnordgren
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
MODULESHOME=/usr/share/Modules
MANPATH=:
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.S7MBH0
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GDM_LANG=en_US.UTF-8
HOME=/home/bnordgren
USERNAME=bnordgren
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:
XDG_CURRENT_DESKTOP=GNOME
VTE_VERSION=5803
WAYLAND_DISPLAY=wayland-0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/f3b1d89c_0830_4ca4_a172_defb469b1d7a
INVOCATION_ID=9771407b5939476987ef5c101825f2dc
MANAGERPID=984
GJS_DEBUG_OUTPUT=stderr
MODULEPATH_modshare=/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1
XDG_SESSION_CLASS=user
TERM=xterm-256color
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=bnordgren
GNOME_TERMINAL_SERVICE=:1.122
MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH
LOADEDMODULES=
DISPLAY=:0
SHLVL=0
QT_IM_MODULE=ibus
XDG_RUNTIME_DIR=/run/user/1000
JOURNAL_STREAM=9:42397
XDG_DATA_DIRS=/home/bnordgren/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
PATH=/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/bnordgren/.local/bin:/home/bnordgren/bin
MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
GDMSESSION=gnome
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/bnordgren
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
BASH_FUNC_switchml%%=() {  typeset swfound=1;
 if [ "${MODULES_USE_COMPAT_VERSION:-0}" = '1' ]; then
 typeset swname='main';
 if [ -e /usr/share/Modules/libexec/modulecmd.tcl ]; then
 typeset swfound=0;
 unset MODULES_USE_COMPAT_VERSION;
 fi;
 else
 typeset swname='compatibility';
 if [ -e /usr/share/Modules/libexec/modulecmd-compat ]; then
 typeset swfound=0;
 MODULES_USE_COMPAT_VERSION=1;
 export MODULES_USE_COMPAT_VERSION;
 fi;
 fi;
 if [ $swfound -eq 0 ]; then
 echo "Switching to Modules $swname version";
 source /usr/share/Modules/init/bash;
 else
 echo "Cannot switch to Modules $swname version, command not found";
 return 1;
 fi
}
BASH_FUNC_scl%%=() {  if [ "$1" = "load" -o "$1" = "unload" ]; then
 eval "module $@";
 else
 /usr/bin/scl "$@";
 fi
}
_=/usr/bin/env
XXX1=foobar
```

**Comment by riccardomurri** [comment] 2020-03-11 07:52
Ok, so `XXX2` which is a multi-line variable is absent from the output.  Good.  Now, why are the exported function definitions, which are multi-line too, not filtered out?

**Comment by riccardomurri** [comment] 2020-03-11 07:57
I cannot reproduce your shell's behavior on my computer; if I define a
function and export it, the `env -0 | awk` trick filters it out
correctly:

```
 $ xxx () { echo "xxx"; }

 $ export -f xxx

 $ env | fgrep xxx
BASH_FUNC_xxx%%=() {  echo "xxx"

 $ env -0 | awk 'BEGIN { RS="\0"; FS="="; }; { if ($2 !~ /\n/) print; };' | (fgrep xxx || echo "xxx not found")
xxx not found
```

**Comment by riccardomurri** [comment] 2020-03-11 08:02
Can you please run these commands in the shell where you're running ElastiCluster and post their output?

```
type -a env 
declare -F
```

**Comment by bnordgren** [comment] 2020-03-11 19:16
I may have a better solution: The following Dockerfile reproduces my behavior. Can't actually run docker from within the container, but the weird behavior is present. 

```
FROM fedora:31

RUN dnf install -y environment-modules wget && \
    wget https://github.com/elasticluster/elasticluster/raw/bb4a3278cf01cc1619718caaa98f212b4b7ecfaa/elasticluster.sh && \
    chmod a+x elasticluster.sh && \
    mv elasticluster.sh elasticluster && \
    echo "alias docker=podman" >> /root/.bashrc && \
    ln -s /bin/false /usr/bin/docker && \
    useradd testuser
```

After building (and in my case, tagging the image 'elasticluster'), you should be able to...

```
[bnordgren@mine elasticluster]$ podman run -ti --rm elasticluster bash
[root@f0907e5bc893 /]# su testuser
[testuser@f0907e5bc893 /]$ ./elasticluster 
mkdir: created directory '/home/testuser/.ssh'
mkdir: created directory '/home/testuser/.elasticluster'
[testuser@f0907e5bc893 /]$ ls /tmp
elasticluster.LPqdnde2RXFp.env  ks-script-8thrj8v5
[testuser@f0907e5bc893 /]$ cat /tmp/elasticluster.LPqdnde2RXFp.env 
...
```

**Comment by riccardomurri** [comment] 2020-03-11 20:31
Thanks a lot for the Dockerfile; the issue is now solved -- you'll need to download the script again from the "master" branch to get the fixed one.

In retrospect, the problem was obvious: if `=` occurs in the value of an environmental variable, then `awk` would split the line multiple times, so testing for newlines in `$2` is not enough: it fails, e.g., on:

    BASH_FUNC_scl%%=() {  if [ "$1" = "load" -o "$1" = "unload" ]; then

because then `awk`'s `$2` would be the string `() {  if [ "$1" ` which contains no newlines...

**Closed** 2020-03-11 20:31 UTC
